INSERT INTO todos (title, description, completed, created_at, updated_at) VALUES
                                                                              ('Học Spring Boot', 'Tìm hiểu Spring Web và REST API', false, NOW(), NOW()),
                                                                              ('Học JPA', 'Làm việc với Spring Data JPA', true, NOW(), NOW()),
                                                                              ('Thiết kế database', 'Thiết kế bảng Todo', false, NOW(), NOW()),
                                                                              ('Viết API CRUD', 'Hoàn thành Create Read Update Delete', true, NOW(), NOW()),
                                                                              ('Tích hợp PostgreSQL', 'Kết nối database', false, NOW(), NOW()),
                                                                              ('Viết Validation', 'Kiểm tra dữ liệu đầu vào', false, NOW(), NOW()),
                                                                              ('Xử lý Exception', 'Global Exception Handler', true, NOW(), NOW()),
                                                                              ('Viết README', 'Hướng dẫn cài đặt dự án', false, NOW(), NOW()),
                                                                              ('Push GitHub', 'Đưa source lên GitHub', true, NOW(), NOW()),
                                                                              ('Test Postman', 'Kiểm thử API', false, NOW(), NOW()),
                                                                              ('Thiết kế giao diện', 'Làm UI React', false, NOW(), NOW()),
                                                                              ('Responsive', 'Tối ưu giao diện điện thoại', true, NOW(), NOW()),
                                                                              ('Tìm kiếm Todo', 'Search theo tiêu đề', false, NOW(), NOW()),
                                                                              ('Lọc trạng thái', 'Filter completed và pending', true, NOW(), NOW()),
                                                                              ('Viết Docker Compose', 'Docker PostgreSQL', false, NOW(), NOW()),
                                                                              ('Deploy Backend', 'Deploy lên Render', false, NOW(), NOW()),
                                                                              ('Deploy Frontend', 'Deploy lên Vercel', true, NOW(), NOW()),
                                                                              ('Viết Unit Test', 'JUnit cho Service', false, NOW(), NOW()),
                                                                              ('Refactor Code', 'Tối ưu source code', true, NOW(), NOW()),
                                                                              ('Chuẩn bị phỏng vấn', 'Ôn Java Core và SQL', false, NOW(), NOW());